CREATE TABLE IF NOT EXISTS Users (
  userId INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255),
  password VARCHAR(255),
  fullName VARCHAR(255),
  emailAddress VARCHAR(255),
  phoneNumber VARCHAR(20),
  address VARCHAR(255),
  role VARCHAR(255),
  rating INT,
  numberOfViews INT,
  accountStatus BOOLEAN,
  paymentInformation INT,
  email VARCHAR(255),
  profilePicture MEDIUMBLOB,
  introduction TEXT,
  location VARCHAR(255),
  skill VARCHAR(255),
  proficiency VARCHAR(255),
  availability VARCHAR(255),
  preference VARCHAR(255),
  company VARCHAR(255),
  position VARCHAR(255),
  timeOfWork VARCHAR(255),
  reference VARCHAR(255),
  certificate MEDIUMBLOB,
  education VARCHAR(255),
  payment VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
